service: companies-api-lambda

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    MONGODB_URI: {env:MONGODB_URI}

plugins:
  - serverless-offline

functions:
  createCompany:
    handler: dist/handlers/create-company.handler
    events:
      - http:
          path: companies
          method: post

package:
  exclude:
    - .git/**
    - node_modules/**
    - .env
    - .env.example
    - '*.md'
    - tests/**
    - .gitignore
    - setup.sh
    - .DS_Store

